### ISSUE TITLE
Change server to support the pcd-passport api instead of interep

### ISSUE THREAD

**Issue by AtHeartEngineer** [Rate-Limiting-Nullifier/zk-chat-client-server#3]
Copy the [server-lib interep impementation](https://github.com/Rate-Limiting-Nullifier/zk-chat-client-server/tree/main/zk-chat-server-lib/src/interrep) to a `pcd` implementation that fetches `https://api.pcd-passport.com/semaphore/1` instead of the interep api.

**Comment by NicoSerranoP** [comment]
I will start here to understand the app better :)

**Comment by mhchia** [comment]
Resolved too in `main`.
